# Generated by Django 3.2.7 on 2022-04-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('imagen', models.ImageField(null=True, upload_to='perfiles')),
                ('delivery', models.BooleanField(default=False)),
                ('vendedor', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, default='', max_length=32)),
                ('direccion', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(choices=[('A', 'Automovil'), ('M', 'Moto'), ('B', 'Bicicleta')], max_length=1)),
                ('v_marca', models.CharField(max_length=32)),
                ('v_modelo', models.CharField(max_length=32)),
                ('v_color', models.CharField(max_length=16)),
                ('v_placa', models.CharField(max_length=32)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuario')),
            ],
        ),
    ]
