# Generated by Django 3.2.7 on 2022-04-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Perfil',
        ),
        migrations.RenameField(
            model_name='deliver',
            old_name='vehiculo',
            new_name='tipo',
        ),
    ]
