# Generated by Django 3.2.7 on 2022-04-12 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220412_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliver',
            old_name='usuario',
            new_name='perfil',
        ),
    ]
